### ISSUE TITLE
Binary release has dependency on nix install of libiconv

### ISSUE THREAD

**Issue by silid** [hedonhermdev/tune-prism#1]
Great project.

Your binary release requires a nix installed version of libiconv.2.dylib

**Comment by hedonhermdev** [comment]
Nix is being more and more of an annoyance lately. The new binary on the release page should work now. 

If you don't want to redownload, this fix should work:

```bash
brew install libiconv
cp /opt/homebrew/Cellar/libiconv/1.17/lib/{libiconv.2,libcharset.1}.dylib "/Applications/Tune Prism.app/Contents/Frameworks"
install_name_tool -change /nix/store/pb4vbsfgdik0qizna8vrdzk0jv746rgy-libiconv-99/lib/libiconv.2.dylib @rpath/libiconv.2.dylib /Applications/Tune\ Prism.app/Contents/MacOS/Tune\ Prism
```

[Credit](https://www.reddit.com/r/rust/comments/1ea0xpr/comment/leicsla/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
